name: TH
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run a trufflehog scan
      uses: menzew/daction@main
      with:
        scanArguments: "--regex --entropy=True --max_depth=35 --rules /regexes.json" # Add custom options here*
 
