# This is a basic workflow to help you get started with Actions

name: th1
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: trufflehog-scan
      uses: menzew/daction@main
 
